application: eb-gamenight
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /resources
  static_dir: resources

- url: /tasks/.*
  script: gamenight.cron
  login: admin

- url: /.*
  script: gamenight.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: pycrypto
  version: "2.6"
